rockcrafters/java-rockcraft-plugins

README.md, rockcraft-gradle/build.gradle.kts, rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/BaseRockcraftTest.java, rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/RockcraftPluginTest.java, rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/SpringBootTest.java
=> chore: rename plugin

rockcraft/src/main/java/com/canonical/rockcraft/builder/RockCrafter.java
=> feat: order rockcraft.yaml tags

rockcraft-maven/src/it/manual-create-rock-test/pom.xml, rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/PushRockMojo.java
Add push rock mojo for maven plugin.
This needs:
- https://github.com/rockcrafters/java-rockcraft-plugins/pull/8
- https://github.com/rockcrafters/java-rockcraft-plugins/pull/7
-----
=> feat: add push rock mojo

pom.xml, rockcraft-maven/pom.xml, rockcraft-maven/src/it/basic-rock/pom.xml, rockcraft-maven/src/it/manual-create-rock-test/pom.xml, rockcraft/pom.xml
- rename the groupId to `io.github.rockcrafters` to match the repository location
- bump version number to `0.2.1` to match gradle plugin
-----
=> chore: rename groupId and bump version of the maven plugin.

.github/workflows/build.yml, .github/workflows/release.yml, pom.xml
Samples failed to build due to maven release pipeline MR merged first. 
Add release profile in the pom.xml to sign only builds.
-----
=> fix: resolve failure to build samples

.github/workflows/release.yml
=> chore: do not publish to maven central yet

.github/workflows/release-github.yml, .github/workflows/release-gradle.yml, .github/workflows/release-maven.yml, build.gradle.kts
Split release pipelines into:
- gradle pipeline
- maven pipeline
Add github packages pipeline. 
Switch release workflows to the manual trigger.
-----
=> chore: enable github packages packaging.

.github/workflows/release-github.yml, .github/workflows/release-maven.yml
=> fix: fix typos in pipeline definitions

.github/workflows/release-github.yml
=> fix(release-github): remove extra '$'

.github/workflows/release-github.yml
=> fix(github-release): quote variables

.github/workflows/release-github.yml, pom.xml
=> chore: enable publishing maven plugin to Github

pom.xml, rockcraft-maven/pom.xml, rockcraft/pom.xml
Add project information as required by Maven central:
- license
- developers
- scm
- name
- description
-----
=> chore: add project information

README.md, build.gradle.kts, examples/gradle/app-options/build.gradle, examples/gradle/beryx-jlink/build.gradle, examples/gradle/beryx-runtime/build.gradle, examples/gradle/spring-app/build.gradle, examples/maven/custom-rockcraft/pom.xml, examples/maven/shaded-jar/pom.xml, examples/maven/spring-boot-app/pom.xml, pom.xml, rockcraft-maven/pom.xml, rockcraft/pom.xml
No functional changes, increment version. 
-----
=> chore: bump version to 0.2.3

pom.xml
-----
found while trying to rebuild for Reproducible Central
=> fix typo in Git repo url

rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/AbstractRockcraftTask.java, rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/BuildRockcraftTask.java, rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/CreateRockcraftTask.java, rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/RockcraftPlugin.java, rockcraft/src/main/java/com/canonical/rockcraft/builder/AbstractRockCrafter.java, rockcraft/src/main/java/com/canonical/rockcraft/builder/RockBuilder.java
- remove unused imports
- use addAll instead of the loop
- remove unneeded template parameter
- do not use javadoc comments for copyright
-----
=> lint: resolve checkstyle warnings

README.md, build.gradle.kts, examples/gradle/app-options/build.gradle, examples/gradle/beryx-jlink/build.gradle, examples/gradle/beryx-runtime/build.gradle, examples/gradle/spring-app/build.gradle, examples/maven/custom-rockcraft/pom.xml, examples/maven/spring-boot-app/pom.xml, pom.xml, rockcraft-maven/pom.xml, rockcraft/pom.xml
- bump version to 1.0 before merging build rock export
- add missing documentation about dependencies-export task
-----
=> chore: bump version and update documentation

examples/maven/custom-rockcraft/pom.xml, examples/maven/shaded-jar/pom.xml, examples/maven/spring-boot-app/pom.xml, rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/ArtifactCopy.java, rockcraft-maven/pom.xml, rockcraft-maven/src/it/build-rock/foo/Foo.java, rockcraft-maven/src/it/build-rock/invoker.properties, rockcraft-maven/src/it/build-rock/pom.xml, rockcraft-maven/src/it/build-rock/verify.bsh, rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/CreateBuildRockMojo.java, rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/RockSettingsFactory.java, rockcraft/src/main/java/com/canonical/rockcraft/builder/BuildRockCrafter.java, rockcraft/src/main/java/com/canonical/rockcraft/util/MavenArtifactCopy.java
This PR adds create-build-rock command to maven plugin. 
-----
=> feat: add create-build-rock command to maven plugin

README.md, build.gradle.kts, examples/gradle/app-options/build.gradle, examples/gradle/beryx-jlink/build.gradle, examples/gradle/beryx-runtime/build.gradle, examples/gradle/spring-app/build.gradle, examples/maven/custom-rockcraft/pom.xml, examples/maven/shaded-jar/pom.xml, examples/maven/spring-boot-app/pom.xml, pom.xml, rockcraft-maven/pom.xml, rockcraft/pom.xml
Update version to 1.1.0.
-----
=> chore: start version 1.1.0

rockcraft/src/main/java/com/canonical/rockcraft/builder/BuildRockCrafter.java
- install `git` slice to be able to clone project inside the container
- add base_file_chisel for the manifest
-----
=> fix: add missing slices: git and chisel manifest

rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/CreateBuildRockTest.java, rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/build-rockcraft.in, rockcraft/src/main/java/com/canonical/rockcraft/builder/AbstractRockCrafter.java, rockcraft/src/main/java/com/canonical/rockcraft/builder/BuildRockCrafter.java, rockcraft/src/main/java/com/canonical/rockcraft/builder/RockBuilder.java, rockcraft/src/main/java/com/canonical/rockcraft/builder/RockCrafter.java
This was missing from the implementation - the parts section was not merged properly with the snippet, but rather overridden.
-----
=> fix: allow overriding build rock parts

examples/maven/spring-boot-app/pom.xml, rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/PushBuildRockcraftTask.java, rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/RockcraftPlugin.java, rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/BuildBuildRockMojo.java, rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/PushBuildRockMojo.java
This PR adds `build-build-rock` and `push-build-rock` goals to Maven plugin and `push-build-rock` goal to Gradle plugin.
-----
=> feat: add push build rock task for gradle

rockcraft/src/main/resources/com/canonical/rockcraft/builder/build-gradle.sh
=> fix: add missing quotes in build goal

README.md
Use `setRockcraftYaml` instead of `rockcraftYaml =`
-----
=> doc: fix kotlin plugin configuration

rockcraft/src/main/java/com/canonical/rockcraft/builder/AbstractRockCrafter.java
=> fix: throw exception if rockcraft yaml can not be parsed

README.md, build.gradle.kts, examples/gradle/app-options/build.gradle, examples/gradle/beryx-jlink/build.gradle, examples/gradle/beryx-runtime/build.gradle, examples/gradle/spring-app/build.gradle, examples/maven/custom-rockcraft/pom.xml, examples/maven/shaded-jar/pom.xml, examples/maven/spring-boot-app/pom.xml, pom.xml, rockcraft-maven/pom.xml, rockcraft/pom.xml
=> chore: start 1.1.1 version

README.md, build.gradle.kts, examples/gradle/app-options/build.gradle, examples/gradle/beryx-jlink/build.gradle, examples/gradle/beryx-runtime/build.gradle, examples/gradle/spring-app/build.gradle, examples/maven/custom-rockcraft/pom.xml, examples/maven/shaded-jar/pom.xml, examples/maven/spring-boot-app/pom.xml, pom.xml, rockcraft-maven/pom.xml, rockcraft/pom.xml
Bump version to fix https://github.com/rockcrafters/java-rockcraft-plugins/pull/98
-----
=> chore: bump version to 1.1.2

.github/workflows/build.yml, .github/workflows/release-github.yml, .github/workflows/release-gradle.yml, .github/workflows/release-maven.yml
=> fix: set workflow permissions

rockcraft/src/main/java/com/canonical/rockcraft/builder/AbstractRockCrafter.java, rockcraft/src/main/java/com/canonical/rockcraft/builder/RockNameUtil.java, rockcraft/src/test/java/com/canonical/rockcraft/builder/RockNameUtilTest.java
Fixes: https://github.com/rockcrafters/java-rockcraft-plugins/issues/109
-----
=> fix: transform project names into rock name.

rockcraft/src/main/java/com/canonical/rockcraft/builder/RockBuilder.java
=> fix: provide error message if rock not found

rockcraft-maven/pom.xml
This allows shorthands like `mvn rockcraft:create-rock`
-----
=> feat(maven): add plugin prefix

README.md, examples/maven/spring-boot-app/pom.xml, rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/CreateBuildRockcraftTask.java, rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/CreateBuildRockTest.java, rockcraft-maven/src/it/build-rock/pom.xml, rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/CreateBuildRockMojo.java, rockcraft/build.gradle.kts, rockcraft/pom.xml, rockcraft/src/main/java/com/canonical/rockcraft/builder/BuildRockCrafter.java, rockcraft/src/main/java/com/canonical/rockcraft/builder/BuildRockcraftOptions.java, rockcraft/src/main/java/com/canonical/rockcraft/util/BuildRunner.java, rockcraft/src/main/java/com/canonical/rockcraft/util/POMUtil.java, rockcraft/src/main/resources/com/canonical/rockcraft/builder/build-gradle.sh, rockcraft/src/main/resources/com/canonical/rockcraft/builder/build-maven.sh, rockcraft/src/main/resources/com/canonical/rockcraft/builder/settings.xml, rockcraft/src/test/java/com/canonical/rockcraft/builder/BuildRockCrafterTest.java, rockcraft/src/test/java/com/canonical/rockcraft/builder/POMUtilTest.java
Rework build rock export:
- build maven project with specified goal instead of using offline plugin
- add user with uid:gid 1000:1000 to allow mapping
- fix path to maven executable
- update documentation
-----
=> feat: rework maven build rock generation

README.md, build.gradle.kts, examples/gradle/app-options/build.gradle, examples/gradle/beryx-jlink/build.gradle, examples/gradle/beryx-runtime/build.gradle, examples/gradle/spring-app/build.gradle, examples/maven/custom-rockcraft/pom.xml, examples/maven/shaded-jar/pom.xml, examples/maven/spring-boot-app/pom.xml, examples/maven/spring-boot-native/pom.xml, pom.xml, rockcraft-maven/pom.xml, rockcraft/pom.xml
=> bump version to 1.2.0

README.md, build.gradle.kts, examples/gradle/app-options/build.gradle, examples/gradle/beryx-jlink/build.gradle, examples/gradle/beryx-runtime/build.gradle, examples/gradle/spring-app-native/build.gradle, examples/gradle/spring-app/build.gradle, examples/maven/custom-rockcraft/pom.xml, examples/maven/shaded-jar/pom.xml, examples/maven/spring-boot-app/pom.xml, examples/maven/spring-boot-native/pom.xml, pom.xml, rockcraft-maven/pom.xml, rockcraft/pom.xml
=> chore: update current release to 1.2.1

README.md, build.gradle.kts, examples/gradle/app-options/build.gradle, examples/gradle/beryx-jlink/build.gradle, examples/gradle/beryx-runtime/build.gradle, examples/gradle/spring-app-native/build.gradle, examples/gradle/spring-app/build.gradle, examples/maven/custom-rockcraft/pom.xml, examples/maven/shaded-jar/pom.xml, examples/maven/spring-boot-app/pom.xml, examples/maven/spring-boot-native/pom.xml, pom.xml, rockcraft-maven/pom.xml, rockcraft/pom.xml
=> chore: update version to 1.2.2
