- README.md
- SECURITY.md
- rockcraft-gradle/build.gradle.kts
- Fix gradle plugin urls. 
-----
> fix: rename vcs url in plugin description

- rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/PushRockcraftTask.java
- rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/RockcraftPluginTest.java
Fix typo in PushRockcraftTask - it was calling build instead of push.
Add test assertion to validate that the image was indeed pushed.
-----
> fix: fix typo - push task was calling build

- rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/ITaskNames.java
- rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/RockSettingsFactory.java
- rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/RockcraftPlugin.java
- rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/BeryxRuntimeTest.java
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/beryx-runtime-project-build.in
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockCrafter.java
Beryx [runtime](https://github.com/beryx/badass-runtime-plugin) plugin is used for non-modular applications. It needs same implementation as jlink plugin, but requires a different task name - 'runtime'.
Changes:
- add runtime task name
- skip 'jre' output 
- add test for runtime plugin
-----
> feat: support beryx runtime plugin

- .github/workflows/release.yml
- README.md
- build.gradle.kts
- rockcraft-gradle/build.gradle.kts
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/alloptions.in
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/architecture.in
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/beryx-project-build.in
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/beryx-runtime-project-build.in
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/build-rock-java-11.in
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/default-build.in
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/rockcraft-plugin-options.in
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/single-rock1.in
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/single-rock2.in
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/spring-boot-project.in
Plugin was rejected due to invalid coordinates. 
- Update coordinates. 
- Use team publishing secret.
- Bump version
-----
> chore: rename plugin (gradle plugin portal reject)

- rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/BeryxJLinkTest.java
- rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/BeryxRuntimeTest.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockCrafter.java
- The application image was not copied correctly because the command missed ${CRAFT_PART_INSTALL}.
- The startup flag was not specified
- Launcher dependencies were missing
-----
> fix: running app image with beryx plugins

- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/AbstractRockMojo.java
Maven plugin had some options missing
-----
> fix: pass missing options to RockCraftOptions

- .github/workflows/build.yml
- .github/workflows/release.yml
- pom.xml
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/AbstractRockMojo.java
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/BuildRockMojo.java
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/CreateRockMojo.java
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/PushRockMojo.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockBuilder.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockProjectSettings.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockcraftOptions.java
- rockcraft/src/main/java/com/canonical/rockcraft/util/MapMerger.java
This PR enables maven central publishing workflow.
Changes:
- Add missing javadoc comments 
- Enable javadoc and sources packaging for maven plugin
- Add maven central publishing plugin
- Enable gpg signing
- Add release workflow step for maven
- Remove `release` property as it was interfering with javadoc generation using Java 8.
-----
> chore: enable maven publishing

- rockcraft/src/main/java/com/canonical/rockcraft/builder/RawRuntimePart.java
- rockcraft/src/test/java/com/canonical/rockcraft/builder/RawRunimePartTest.java
JLink rockcraft plugin adds all jars found in staging area to jlink arguments. Since we know artifact in maven/gradle plugin it is sufficient to add them to the classpath.
-----
> fix: set up classpath in line with jlink plugin

- pom.xml
- rockcraft-gradle/build.gradle.kts
- rockcraft-maven/pom.xml
- rockcraft/build.gradle.kts
- rockcraft/pom.xml
We need to ensure that building from source will produce the same binaries:
- name maven and gradle rockcraft library differently to avoid mismatching binaries
- enable reproducible builds for maven
- enable reproducible builds for gradle
- explicitly call out jar plugin version to ensure that correct version is pulled in
-----
> chore: ensure consistent publishing

- README.md
- build.gradle.kts
- examples/gradle/app-options/build.gradle
- examples/gradle/beryx-jlink/build.gradle
- examples/gradle/beryx-runtime/build.gradle
- examples/gradle/spring-app/build.gradle
- examples/maven/custom-rockcraft/pom.xml
- examples/maven/shaded-jar/pom.xml
- examples/maven/spring-boot-app/pom.xml
- pom.xml
- rockcraft-gradle/build.gradle.kts
- rockcraft-maven/pom.xml
- rockcraft/pom.xml
- main library (rockcraft) is not yet published anywhere so it is impossible to reference it from the plugin. 
This makes version 0.2.1 unusable. 
Changes:
- bump version to 0.2.2
- apply shadow jar plugin
-----
> fix: use shadow jar to package dependencies

- .github/workflows/build.yml
Changes:
- run apt update before installing openjdk-8 package.
-----
> chore: run apt update before install

- rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/RockSettingsFactory.java
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/AbstractRockMojo.java
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/RockSettingsFactory.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/AbstractRockCrafter.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/CommonRockcraftOptions.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/Generator.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockArchitecture.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockCrafter.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockProjectSettings.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockcraftOptions.java
In order to start development of build/test rock generator, extract common code:
- Move architecture enums to the top level 
- Introduce generator enum and use it in settings
- introduce abstract base class for RockCrafter
- extract common options for rock generations 
-----
> chore: extract common options for rockcraft settings

- rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/DependencyExportTask.java
- rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/RockcraftPlugin.java
- rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/DependencyExportTest.java
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/dependencies-build.in
- rockcraft/src/main/java/com/canonical/rockcraft/builder/DependencyOptions.java
This PR adds `dependency-export` task that stores project dependencies needed to compile and test the application under `buildDir/dependencies` as an offline maven repository.
-----
> feat: add dependency task

- README.md
- rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/BuildBuildRockcraftTask.java
- rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/CreateBuildRockcraftTask.java
- rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/RockSettingsFactory.java
- rockcraft-gradle/src/main/java/com/canonical/rockcraft/gradle/RockcraftPlugin.java
- rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/CreateBuildRockTest.java
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/build-rockcraft-options.in
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/AbstractRockMojo.java
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/BuildRockMojo.java
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/CreateRockMojo.java
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/PushRockMojo.java
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/RockSettingsFactory.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/AbstractRockCrafter.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/BuildRockCrafter.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/BuildRockcraftOptions.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/BuildSystem.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockBuilder.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockCrafter.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockProjectSettings.java
- rockcraft/src/test/java/com/canonical/rockcraft/builder/BuildRockCrafterTest.java
- chores: renamed Generator -> BuildSystem
- feat: build rock support. 
- this adds two new tasks `create-build-rock` that exports dependencies and creates `build/build-rock/rockcraft.yaml` and `build-build-rock` that writes an oci container
-----
> feat: implement build rock support for gradle

- rockcraft/src/main/java/com/canonical/rockcraft/builder/BuildRockCrafter.java
- rockcraft/src/main/resources/com/canonical/rockcraft/builder/build-gradle.sh
- rockcraft/src/main/resources/com/canonical/rockcraft/builder/build-maven.sh
- rockcraft/src/main/resources/com/canonical/rockcraft/builder/local-build.gradle
- Gradle build might not have maven local configured for the build rock, add init script to configure mavenLocal(). 
- Add 'build' script that can be used as a generic command in build rock: `build <directory-in-container> [ tasks/goals] `.
-----
> feat: add gradle init script to configure maven local repository

- rockcraft/src/main/resources/com/canonical/rockcraft/builder/build-gradle.sh
- rockcraft/src/main/resources/com/canonical/rockcraft/builder/build-maven.sh
This PR sets environment variables in `build` script, so that the user could use it using the chiselled build container.
This fixes the following issue:
```
docker run -v `pwd`:`pwd` --user $(id -u):$(id -g) --env PEBBLE=/tmp build-demo exec build `pwd` --no-daemon
```
Resulted in
```
FAILURE: Build failed with an exception.
...
* What went wrong:
Plugin [id: 'io.github.rockcrafters.rockcraft', version: '1.1.0'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (No included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'io.github.rockcrafters.rockcraft:io.github.rockcrafters.rockcraft.gradle.plugin:1.1.0')
Searched in the following repositories:
Gradle Central Plugin …
```
> fix: set environment variables.

- rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/CreateBuildRockTest.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/BuildRockCrafter.java
The names of runtime rock and the build rock were the same, so the push task was overwriting the image.
I have added `build-` prefix to the build rock name. 
-----
> fix: add build- prefix to the build rock

- rockcraft-gradle/src/test/java/com/canonical/rockcraft/gradle/RockcraftPluginTest.java
- rockcraft-gradle/src/test/resources/com/canonical/rockcraft/gradle/rockcraft.in
- rockcraft/src/main/java/com/canonical/rockcraft/builder/JLinkRuntimePart.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RawRuntimePart.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockcraftOptions.java
- rockcraft/src/test/java/com/canonical/rockcraft/builder/RawRunimePartTest.java
JLink plugin is now part of rockcraft and is enabled by default.
Updated RawRuntimePart codegeneration (copy paste from jlink plugin implementation)
-----
> chore: enable jlink plugin

- examples/maven/spring-boot-app/README.md
Add missing '/' in the run command for https://github.com/rockcrafters/java-rockcraft-plugins/issues/101
-----
> fix: fix command for running the rock

- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/RockSettingsFactory.java
- rockcraft/src/main/java/com/canonical/rockcraft/builder/RockNameUtil.java
- rockcraft/src/test/java/com/canonical/rockcraft/builder/RockNameUtilTest.java
Fixes: https://github.com/rockcrafters/java-rockcraft-plugins/issues/111
Gradle uses project name which translates to the artifact id of the output. Maven was using display name which does not map well into rock name. Artifact ids has same constraints as rock names:
https://maven.apache.org/guides/mini/guide-naming-conventions.html only characters, digits and hyphens are allowed. There is no 40 character size constraint.
Changes:
- use artifact id for the maven rock name
- truncate rock name to 40 symbols
- Keep name sanitiser
- Return "rock" instead of the exception if the name can not be sanitised.
This addresses:
https://github.com/rockcrafters/java-rockcraft-plugins/issues/109
-----
> fix: use artifact id for maven rock name

- rockcraft-maven/pom.xml
- rockcraft-maven/src/it/build-rock/pom.xml
- rockcraft-maven/src/it/build-rock/verify.bsh
- rockcraft-maven/src/main/java/com/canonical/rockcraft/maven/CreateBuildRockMojo.java
The implementation was calling model.getDependencies() which returned only direct dependencies of the project. Inherit from GoOffline mojo of Maven Dependency Plugin to retrieve full list of the dependencies.
-----
> fix: export transitive dependencies in maven build rock

- rockcraft-gradle/build.gradle.kts
Reverts rockcrafters/java-rockcraft-plugins#139 - The updated version requires Java 11
> Revert "chore(deps): update plugin com.gradleup.shadow to v9.0.2"
